[package]
name = "data-composer"
version = "1.0.1"
authors = ["pewpew79 <grigoriev.d3@mail.ru>"]
edition = "2018"


[dependencies]
log = "0.4.8"
serde_json = "1.0.41"
serde_yaml = "0.8.11"
#mongodb = "0.9.0"
mongodb = "0.4.0"
bson = "0.14.0"
data-finder = { git = "https://github.com/pewpew79/data-finder.git", branch = "master" }
data-getter = { git = "https://github.com/pewpew79/data-getter.git", branch = "master" }
